{"name": "test_zhs_seleniumlogintest", "status": "broken", "statusDetails": {"message": "TypeError: __init__() got an unexpected keyword argument 'chromedriver'", "trace": "self = <testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest object at 0x000001FECE7A0BE0>\n\n    def test_zhs_seleniumlogintest(self):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        chrome_options = webdriver.FirefoxOptions()\n        chrome_options.add_argument(\"--headless\")\n        chromedriver_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),\n                                         \"config\\chromedriver.exe\")\n        logger.info(chromedriver_path)\n>       browser = webdriver.Chrome(chromedriver=chromedriver_path, chrome_options=chrome_options)\nE       TypeError: __init__() got an unexpected keyword argument 'chromedriver'\n\ntest_zhs_seleniumlogintest.py:26: TypeError"}, "attachments": [{"name": "log", "source": "b9bee982-8ea1-433d-82b0-e4a1bcebcf06-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "076483b1-8949-4765-ae5f-5d3f4be60e07-attachment.txt", "type": "text/plain"}], "start": 1624430497986, "stop": 1624430497987, "uuid": "c92c97be-e92b-49df-9b56-7ef53118448c", "historyId": "c06aec85e63e41e2b940ef2c08025c58", "testCaseId": "e6ed18b5be4e055550dc72885e918ffe", "fullName": "testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest#test_zhs_seleniumlogintest", "labels": [{"name": "parentSuite", "value": "testcases.user"}, {"name": "suite", "value": "test_zhs_seleniumlogintest"}, {"name": "subSuite", "value": "Test_seleniumlogintest"}, {"name": "host", "value": "DESKTOP-FRVNKTB"}, {"name": "thread", "value": "3816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user.test_zhs_seleniumlogintest"}]}