{"name": "test_zhs_seleniumlogintest", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\\\worksapce\\\\pytest\\\\pytestDemo-master\\\\config\\\\cgeckodriver.exe'", "trace": "self = <testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest object at 0x00000242049A0460>\n\n    def test_zhs_seleniumlogintest(self):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        chromedriver_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),\n                                         \"config\\chromedriver.exe\")\n        logger.info(chromedriver_path)\n        # browser = webdriver.Chrome(chromedriver_path)\n        firefoxdriver_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),\n                                          \"config\\cgeckodriver.exe\")\n        logger.info(firefoxdriver_path)\n>       browser = webdriver.Firefox(firefoxdriver_path)\n\ntest_zhs_seleniumlogintest.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:151: in __init__\n    firefox_profile = FirefoxProfile(firefox_profile)\n..\\..\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\firefox_profile.py:79: in __init__\n    shutil.copytree(self.profile_dir, newprof,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nsrc = 'C:\\\\worksapce\\\\pytest\\\\pytestDemo-master\\\\config\\\\cgeckodriver.exe'\ndst = 'C:\\\\Users\\\\able\\\\AppData\\\\Local\\\\Temp\\\\tmplqihw9uh\\\\webdriver-py-profilecopy'\nsymlinks = False\nignore = <function ignore_patterns.<locals>._ignore_patterns at 0x0000024204C5BA60>\ncopy_function = <function copy2 at 0x0000024201822700>\nignore_dangling_symlinks = False, dirs_exist_ok = False\n\n    def copytree(src, dst, symlinks=False, ignore=None, copy_function=copy2,\n                 ignore_dangling_symlinks=False, dirs_exist_ok=False):\n        \"\"\"Recursively copy a directory tree and return the destination directory.\n    \n        dirs_exist_ok dictates whether to raise an exception in case dst or any\n        missing parent directory already exists.\n    \n        If exception(s) occur, an Error is raised with a list of reasons.\n    \n        If the optional symlinks flag is true, symbolic links in the\n        source tree result in symbolic links in the destination tree; if\n        it is false, the contents of the files pointed to by symbolic\n        links are copied. If the file pointed by the symlink doesn't\n        exist, an exception will be added in the list of errors raised in\n        an Error exception at the end of the copy process.\n    \n        You can set the optional ignore_dangling_symlinks flag to true if you\n        want to silence this exception. Notice that this has no effect on\n        platforms that don't support os.symlink.\n    \n        The optional ignore argument is a callable. If given, it\n        is called with the `src` parameter, which is the directory\n        being visited by copytree(), and `names` which is the list of\n        `src` contents, as returned by os.listdir():\n    \n            callable(src, names) -> ignored_names\n    \n        Since copytree() is called recursively, the callable will be\n        called once for each directory that is copied. It returns a\n        list of names relative to the `src` directory that should\n        not be copied.\n    \n        The optional copy_function argument is a callable that will be used\n        to copy each file. It will be called with the source path and the\n        destination path as arguments. By default, copy2() is used, but any\n        function that supports the same signature (like copy()) can be used.\n    \n        \"\"\"\n        sys.audit(\"shutil.copytree\", src, dst)\n>       with os.scandir(src) as itr:\nE       FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\\\worksapce\\\\pytest\\\\pytestDemo-master\\\\config\\\\cgeckodriver.exe'\n\nC:\\Users\\able\\AppData\\Local\\Programs\\Python\\Python39\\lib\\shutil.py:555: FileNotFoundError"}, "attachments": [{"name": "log", "source": "e3de95ba-7cb9-4153-ad35-0f57cf7f8639-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1aeab2d3-3199-4e31-8fec-1634d12ae4c1-attachment.txt", "type": "text/plain"}], "start": 1624429580254, "stop": 1624429580256, "uuid": "42ece8d1-b581-4395-9788-c627b1ebeca2", "historyId": "c06aec85e63e41e2b940ef2c08025c58", "testCaseId": "e6ed18b5be4e055550dc72885e918ffe", "fullName": "testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest#test_zhs_seleniumlogintest", "labels": [{"name": "parentSuite", "value": "testcases.user"}, {"name": "suite", "value": "test_zhs_seleniumlogintest"}, {"name": "subSuite", "value": "Test_seleniumlogintest"}, {"name": "host", "value": "DESKTOP-FRVNKTB"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user.test_zhs_seleniumlogintest"}]}