{"name": "test_zhs_login[13592540004-Aa123456-True-1-except_msg0]", "status": "broken", "statusDetails": {"message": "TypeError: login() missing 1 required positional argument: 'self'", "trace": "self = <testcases.user.test_zhs_Login.TestzhsLogin object at 0x0000016E114A50D0>\naccount = '13592540004', password = 'Aa123456', except_result = True\nexcept_status = 1\nexcept_msg = {'pwd': 'df4da95099ee4510a4fabea36b430c9c', 'status': 1, 'uuid': 'EY6W3opP'}\n\n    @allure.story(\"用例--模拟用户登录的test测试\")\n    @allure.description(\"该用例用户登录的test测试\")\n    @allure.issue(\"https://passport.zhihuishu.com/user/validateAccountAndPassword\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://passport.zhihuishu.com/user/validateAccountAndPassword\", name=\"点击，跳转到对应用例的链接地址\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"account,password,except_result, except_status, except_msg\",\n                             api_data[\"test_zhs_login\"])\n    def test_zhs_login(self, account, password, except_result, except_status, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        step_1()\n        # account = \"13592540004\"\n        # password = \"Aa123456\"\n        # except_result = True\n        # except_status = 1\n        # except_msg = {'pwd': 'df4da95099ee4510a4fabea36b430c9c', 'uuid': 'EY6W3opP', 'status': 1}\n>       result = zhs_login(account, password)\n\ntest_zhs_Login.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\naccount = '13592540004', password = 'Aa123456'\n\n    def zhs_login(account, password):\n        \"\"\"\n        登录用户\n        :param account: 用户名\n        :param password: 密码\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        result = ResultBase()\n        payload = {\n            \"account\": account,\n            \"password\": password\n        }\n        header = {\n            \"Content-Type\": \"application/x-www-form-urlencoded\"\n        }\n>       res = User.login(data=payload, headers=header)\nE       TypeError: login() missing 1 required positional argument: 'self'\n\n..\\..\\operation\\user\\login.py:21: TypeError"}, "description": "该用例用户登录的test测试", "steps": [{"name": "步骤1 ==>> 登录", "status": "passed", "start": 1623381860676, "stop": 1623381860676}], "attachments": [{"name": "log", "source": "2ebcee47-9c8b-46d5-929f-aac6373fdde1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "21dc2b40-7b25-4221-b164-a653f0666970-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "account", "value": "'13592540004'"}, {"name": "password", "value": "'Aa123456'"}, {"name": "except_result", "value": "True"}, {"name": "except_status", "value": "1"}, {"name": "except_msg", "value": "{'pwd': 'df4da95099ee4510a4fabea36b430c9c', 'uuid': 'EY6W3opP', 'status': 1}"}], "start": 1623381860676, "stop": 1623381860677, "uuid": "e3b49bcf-dd0e-44dc-9b02-86708a51b331", "historyId": "e97d7b3a517cad99412d59c034c4382c", "testCaseId": "3716e12e0b146c37eb19dc96812eaa6c", "fullName": "testcases.user.test_zhs_Login.TestzhsLogin#test_zhs_login", "labels": [{"name": "feature", "value": "获取用户信息模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "trivial"}, {"name": "story", "value": "用例--模拟用户登录的test测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.user"}, {"name": "suite", "value": "test_zhs_Login"}, {"name": "subSuite", "value": "TestzhsLogin"}, {"name": "host", "value": "DESKTOP-FRVNKTB"}, {"name": "thread", "value": "16780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user.test_zhs_Login"}], "links": [{"type": "test_case", "url": "https://passport.zhihuishu.com/user/validateAccountAndPassword", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://passport.zhihuishu.com/user/validateAccountAndPassword", "name": "点击，跳转到对应BUG的链接地址"}]}