{"name": "test_test", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_test' object has no attribute 'base_data'", "trace": "self = <testcases.test.Test_test object at 0x000001CE548EE130>\n\n    def test_test(self):\n        # chrome_options = webdriver.ChromeOptions()\n        # chrome_options.add_argument(\"--headless\")\n        # chrome_options.add_argument(\"--no-sandbox\")\n        # chromedriver_path = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))),\n        #                                  \"config\\chromedriver.exe\")\n        # logger.info(chromedriver_path)\n        # logger.info(chrome_options)\n        # browser = webdriver.Chrome(chromedriver_path, options=chrome_options)\n        # browser.get(\n        #     \"https://passport.zhihuishu.com/login?service=https://onlineservice.zhihuishu.com/login/gologin\")\n        # time.sleep(3)\n        # browser.find_element_by_xpath(\"//*[@id='lUsername']\").send_keys(\"13122285260\")\n        # time.sleep(1)\n        # browser.find_element_by_xpath(\"//*[@id='lPassword']\").send_keys(\"Aa111111\")\n        # time.sleep(1)\n        # browser.find_element_by_xpath(\"//*[@id='f_sign_up']/div[1]/span\").click()\n        # time.sleep(3)\n        # list_cookies = browser.get_cookies()\n        # cookies = {}\n        # for s in list_cookies:\n        #     cookies[s[\"name\"]] = s[\"value\"]\n        # browser.quit()\n        # cookies = {\n        #     \"name\": 1\n        # }\n    \n        # BASE_PATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))\n        # yamlpath = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), \"data\\\\base_data.yml\")\n        # data = get_data(yamlpath)\n        # logger.info(data)\n        # for list in data:\n        #     logger.info(list)\n        # with open(yamlpath, \"w\", encoding=\"utf-8\") as f:\n        #     yaml.dump(cookies, f, Dumper=yaml.RoundTripDumper)\n        # return cookies\n>       account = self.base_data[\"init_user_login_teacher\"][\"account\"]\nE       AttributeError: 'Test_test' object has no attribute 'base_data'\n\ntest.py:66: AttributeError"}, "start": 1627463193709, "stop": 1627463193709, "uuid": "5bafdc09-cd71-4bdf-8361-bd52550bd66c", "historyId": "f032f27ee18f9de67a3bb9c16eae57b3", "testCaseId": "03f410e480c0a1872c83a1d8dc4f54f4", "fullName": "testcases.test.Test_test#test_test", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "Test_test"}, {"name": "host", "value": "DESKTOP-FRVNKTB"}, {"name": "thread", "value": "15204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test"}]}